import Head from "next/head";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <style jsx>
        {`
          h1 {
            font-size: 40px;
          }
          h2 {
            font-size: 20px;
          }
          h3 {
            font-size: 15px;
          }
        `}
      </style>
      <Head>
        <title>Keyur's App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/sc.js"></script> */}
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script>{" "} */}
      {/* after all app render then lazyload loaded the file sc.js */}
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Huntin Coder1</h1>
        <img
          src="/download.jpg"
          alt="Next.js Logo"
          width={180}
          height={120}
          className={styles.imageTag}
        />

        <p>A blog for hunting coders by hunting coders</p>
        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript ?</h3>
            <p> javascript is the good langauge for every developer</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript ?</h3>
            <p> javascript is the good langauge for every developer</p>
          </div>{" "}
          <div className="blogItem">
            <h3>How to learn javascript ?</h3>
            <p> javascript is the good langauge for every developer</p>
          </div>{" "}
          <div className="blogItem">
            <h3>How to learn javascript ?</h3>
            <p> javascript is the good langauge for every developer</p>
          </div>{" "}
          <div className="blogItem">
            <h3>How to learn javascript ?</h3>
            <p> javascript is the good langauge for every developer</p>
          </div>
        </div>
      </main>
    </div>
  );
}
